spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

